id = "grapebox-theme"
name = "Grapebox"
version = "0.1.0"
schema_version = 1
authors = ["Jade Fisher"]
description = "Gruvbox, but make it purple"
repository = "https://github.com/fisherrjd/Grapebox"
themes = ["themes/grapebox.json"]
